### ISSUE TITLE
Help on W11 build SO 22621.1702

### ISSUE THREAD

**Issue by El-Barto89** [urob/win-11-virtual-desktop-enhancer#3]
Hi guys, first of alla thanks for this awesome tool. I've been use this tool since W10 and I became addicted due to its power. I cant figure out how to make it work on W11 build SO 22621.1702
Could I ask your help? maybe I'm missing some new step to make it work on W11?
AHK version 1.1.37.01

**Comment by urob** [comment]
I recently updated the library for build 22621.2213. 

Does using the [previous version](https://github.com/urob/win-11-virtual-desktop-enhancer/tree/ffc3e10bb9d1594d581b293b01a432a11570a6d9) work for you?

**Comment by El-Barto89** [comment]
Thank you urob! it was build fault. Thank you for your support!

**Comment by urob** [comment]
Closing as it seems to be resolved
