### ISSUE TITLE
There is a case that cursor remains to be the previous desktop after the latest update

### ISSUE THREAD

**Issue by mrngsht** [urob/win-11-virtual-desktop-enhancer#4]
I love this tool. Thanks as always.
But, after pulling the latest update (https://github.com/urob/win-11-virtual-desktop-enhancer/commit/2d040272c909a00fcb92d9bd322b7afbaf74af72) , It seems for me that something is degraded.

Open Google Spreadsheet with Chrome in desktop1 and Open neovim with Windows Terminal in desktop 2.
Put the cursor in a cell of spread sheet in desktop 1,  then switch to desktop 2, then try to type something on neovim. 
Then I often meet the situation that the cursor remains to be in the cell of spread sheet in desktop 1 and typed characteres are put there, even though I'm facing neovim in desktop 2.

I didn't experience this before the update.
Could you fix this issue?

**Comment by urob** [comment]
Can you test what happens if you disable the tool and use the native windows shortcuts to switch desktops? Does the focus switch correctly then?

**Comment by mrngsht** [comment]
Yes. when using the native shortcut which is Ctrl + Windows + →, it didn't reproduce.

**Comment by urob** [comment]
I just pushed another update to the library if you want to try again

**Comment by mrngsht** [comment]
After pulling the commit, I tried to reproduce this, but it hasn't.
I think the update fixed this issue. 
I appreciate your quick fix!
