### ISSUE TITLE
Windows Update 22631.3155

### ISSUE THREAD

**Issue by dfeneck** [urob/win-11-virtual-desktop-enhancer#6]
New windows 11 build seems to have broken the application, again.

**Comment by mrngsht** [comment]
It's the same for me.

**Comment by urob** [comment]
Does 7cad039 fix it?

**Comment by mrngsht** [comment]
Now fixed in my environment.

**Comment by dfeneck** [comment]
Yup that fixed it for me too. Thankyou.
